# Generated by Django 5.2.3 on 2025-08-15 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.product'),
        ),
        migrations.AddField(
            model_name='myuserproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, through='accounts.MyUserProduct', to='adminDashboard.product'),
        ),
    ]
